### ISSUE TITLE
Query using arxiv id

### ISSUE THREAD

**Issue by shubhamagarwal92** [ourresearch/openalex-api-tutorials#8]
Hi!
Thanks for the nice tutorials! 
Is there an easy way to query the api if we have a list of recent arxiv ids?  How do we align arxiv id with Openalex ids?

**Comment by smierz** [comment]
Hey @shubhamagarwal92 , 
one way would be to construct the corresponding  DOI from your arxiv Id and query the OpenAlex API with it
* here is a [blog post](https://blog.arxiv.org/2022/02/17/new-arxiv-articles-are-now-automatically-assigned-dois/#:~:text=Update%3A%20As%20of%20Feb%202022,arXiv%20articles%20now%20have%20DOIs.&text=DOIs%20(digital%20object%20identifiers)%20are,greater%20interoperability%20with%20other%20services.) describing how to construct the DOI for an arxiv ID 
* use the DOI to [query OpenAlex via it's endpoint for works](https://docs.openalex.org/api-entities/works/filter-works)
* if you have multiple arxiv IDs/DOIs, you may want to [fetch multiple works with one request](https://blog.ourresearch.org/fetch-multiple-dois-in-one-openalex-api-request/)

Hope this helps!
Btw the supported channel for questions is the [OpenAlex Google Group](https://groups.google.com/g/openalex-users), there you'll find more resources and engagement

**Comment by shubhamagarwal92** [comment]
Thanks for your answer! Really helpful!
